#!/bin/bash

# Prerequisites
sudo apt-get update
sudo apt-get install build-essential 
sudo apt-get -y install curl git vim emacs vlc qbittorrent nautilus-dropbox

# Install LaTeX
sudo apt-get install texlive
sudo apt-get install texlive-latex-extra

########## Installing Services + Package Managers ##########

# Install Node.js + NPM
curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -y nodejs

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
sudo apt-get update
sudo apt-get install -y mongodb-org

# Apache2 + MySQL + Composer
sudo apt-get install apache2
sudo apt-get install composer
sudo apt-get install mysql-server

################ Programming Languages ######################

# Install PHP
sudo apt-get install php

# Install Rust 
curl -sSf https://static.rust-lang.org/rustup.sh | sh

# Install Haskell
sudo apt-get install haskell-platform

# Copy and load fonts
mkdir ~/.fonts
cp fonts/* ~/.fonts/
sudo fc-cache -f

# Removing what is unecessary
rm skype-* google-chrome-stable_current_amd64.deb 

