#!/bin/bash

# Prerequisites
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get -y dist-upgrade
sudo apt-get install build-essential 
sudo apt-get -y install curl git vim emacs vlc qbittorrent nautilus-dropbox mysql-workbench-data

#Chrome
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i --force-depends google-chrome-stable_current_amd64.deb

# Skype
wget http://download.skype.com/linux/skype-ubuntu-precise_4.3.0.37-1_i386.deb
sudo dpkg -i skype*

# LAMP Stack + Composer
sudo apt-get -y install apache2
sudo apt-get update
sudo apt-get -y install php libapache2-mod-php7.0 
sudo apt-get -y install mysql-server php7.0-mysql 
sudo apt-get update
sudo apt-get -y install composer

# Node.js
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs

# Haskell
sudo apt-get install haskell-platform

# Final dependencies resolve
sudo apt-get -y -f install

rm skype-* google-chrome-stable_current_amd64.deb 
