#!/bin/bash

# Warning, it will remove your current configurations for Vim!!
# Bash script for setting up configurations and plugins for Vim.

# You need to have installed the following: Vim, gVim(the gtk version). 
# If you don't, just run: sudo pt-get install vim vim-gtk

# Install required dependencies 
sudo apt-get install build-essential cmake curl
sudo apt-get install python-dev python3-dev

curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo npm install -g babel-eslint

# Install the fonts
mkdir ~/.fonts
cp fonts/* ~/.fonts/
sudo fc-cache -f
# PS: You will need to select Ubuntu Mono derivative Powerline from your
#       terminal settings

# Clean start
sudo rm -R ~/.vim					# Remove your current configurations,
sudo rm ~/.vimrc					#   plugins, snippets and so on.

mkdir ~/.vim 
cp -R Vim/colors ~/.vim				# Copy color schemes to vim dir
cp Vim/.vimrc ~/.vim				# Copy .vimrc to .vim dir
cp Vim/plugins.vim ~/.vim                       # Copy the list of plugins

ln -s ~/.vim/.vimrc ~/				# Make a link to be visible to vim

# 1. Copy a file in ~ dir to partially resolve white borders problem in gVim
# 2. Only for atom-dark gVim theme! If you have a diffrent theme, please update
#       the hexa value of "bg[NORMAL] in .gtkrc-2.0 file.
# 3. Only tested in: Mint 18
cp Vim/needed_files/.gtkrc-2.0 ~/
cp Vim/needed_files/.eslintrc ~/

# Get and set Vundle and all the plugins in the plugins in plugins.vim
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall

cd ~/.vim/bundle/YouCompleteMe
python3 install.py --all
# The following error will pop up: "ERROR: msbuild or xbuild is required to build Omnisharp.".
# Don't worry, is from C# and all other features but C# auto-complete will work fine.

# On Fedora execute the following:

# sudo ln -s ~/.vim /root/
# sudo ln -s ~/.vimrc /root/
